package com.egov.secrecysystem.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExRole generated by hbm2java
 */
@DataTransferObject
public class SeProblemPanDuan  implements java.io.Serializable {


     private String id;   
     private String problemnum;
     private String problemlevel;
     private String mustright;
     private String keyproblem;
     private String question;
     private String option1;
     private String option2;
     private String answer;
     
     public SeProblemPanDuan() {
     }
     
     public SeProblemPanDuan(String id) {
    	 this.id = id;  
     }
     
     public SeProblemPanDuan(String id,String problemnum,String problemlevel,String mustright,String keyproblem,String question,String option1,String option2,String answer) {
         this.id = id;  
         this.problemnum = problemnum;
         this.problemlevel = problemlevel;
         this.mustright = mustright;
         this.keyproblem = keyproblem;
         this.question = question;
         this.option1 = option1;
         this.option2 = option2;
         this.answer = answer;    
      }
     
     public String getId() {
 		return id;
 	}


 	public void setId(String id) {
 		this.id = id;
 	}
 
 	
 
     
     public String getProblemnum() {
		return problemnum;
	}

	public void setProblemnum(String problemnum) {
		this.problemnum = problemnum;
	}

	public String getProblemlevel() {
		return problemlevel;
	}
	public void setProblemlevel(String problemlevel) {
		this.problemlevel = problemlevel;
	}
	public String getMustright() {
		return mustright;
	}
	public void setMustright(String mustright) {
		this.mustright = mustright;
	}
	public String getKeyproblem() {
		return keyproblem;
	}
	public void setKeyproblem(String keyproblem) {
		this.keyproblem = keyproblem;
	}
	public String getQuestion() {
		return question;
	}
	public void setQuestion(String question) {
		this.question = question;
	}
	public String getOption1() {
		return option1;
	}
	public void setOption1(String option1) {
		this.option1 = option1;
	}
	public String getOption2() {
		return option2;
	}
	public void setOption2(String option2) {
		this.option2 = option2;
	}
	public String getAnswer() {
		return answer;
	}
	public void setAnswer(String answer) {
		this.answer = answer;
	}
	
	

   
    

}


