package com.egov.secrecysystem.model;


import org.directwebremoting.annotations.DataTransferObject;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1



/**
 * ExUser generated by hbm2java
 */
@DataTransferObject
public class SeUser  implements java.io.Serializable {


     private String id;
     private String name;
     private String loginname;
     private String userlevel;
     private String password;
     private Integer score;
     private String remark;
     private SeRole seRole;
     
 //    private String contactnum;

    public SeUser() {
    }
    
	public SeUser(String id) {
        this.id = id;
    }
    public SeUser(String id, SeRole seRole, String loginname, String password, String name,String userlevel,Integer score) {
       this.id = id;
       this.seRole = seRole;
       this.loginname = loginname;
       this.password = password;
       this.name = name;
       this.userlevel = userlevel;
       this.score = score;
    
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

	
    public String getUserlevel() {
		return userlevel;
	}


	public void setUserlevel(String userlevel) {
		this.userlevel = userlevel;
	}


	public Integer getScore() {
		return score;
	}


	public void setScore(Integer score) {
		this.score = score;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	public SeRole getSeRole() {
		return seRole;
	}


	public void setSeRole(SeRole seRole) {
		this.seRole = seRole;
	}





    public String getLoginname() {
        return this.loginname;
    }
    
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


